# Generated by Django 3.1.2 on 2021-05-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
