# Generated by Django 3.1.2 on 2021-05-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20210502_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
