# Generated by Django 3.1.2 on 2021-05-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_auto_20210502_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='adname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
